(function() {
	'use strict';
	angular
		.module('core')
		.constant('COLOURS', [{
			name: 'Black',
			code: '#000000'
		}, {
			name: 'Blue',
			code: '#0000FF'
		}, {
			name: 'Brown',
			code: '#A52A2A'
		}, {
			name: 'Gold',
			code: '#FFD700'
		}, {
			name: 'Gray',
			code: '#999999'
		}, {
			name: 'Green',
			code: '#4caf50'
		}, {
			name: 'Lime',
			code: '#00FF00'
		}, {
			name: 'Orange',
			code: '#ff9800'
		}, {
			name: 'Pink',
			code: '#e91e63'
		}, {
			name: 'Purple',
			code: '#800080'
		}, {
			name: 'Red',
			code: '#f44336'
		}, {
			name: 'Silver',
			code: '#C0C0C0'
		}, {
			name: 'Violet',
			code: '#EE82EE'
		}, {
			name: 'White',
			code: '#FFFFFF'
		}, {
			name: 'Yellow',
			code: '#FFFF00'
		}, {
			name: 'Azure',
			code: '#00bcd4'
		}]);
}).call(this);